% Marcondes Ricarte

function [scores] = statisticsBlockSetRelevance(Model, i, scores)


   [scores.meanScoreSetRelTrain, scores.meanScoreSetRelTest, ...
        scores.stdScoreSetRelTrain, scores.stdScoreSetRelTest] = ...
        statisticsBetterTrainSetRelevance(Model, scores.scoreTrain, scores.scoreTest, i, 'better_train');

   [scores.meanRatioActivationsSetRelTrain, scores.meanRatioActivationsSetRelTest, ...
        scores.stdRatioActivationsSetRelTrain, scores.stdRatioActivationsSetRelTest] = ...
        statisticsBetterTrainSetRelevance(Model, scores.ratioActivationsTrain, scores.ratioActivationsTest, i, 'better_train');    
    
   [scores.meanRatioCorrectActivationsSetRelTrain, scores.meanRatioCorrectActivationsSetRelTest, ...
        scores.stdRatioCorrectActivationsSetRelTrain, scores.stdRatioCorrectActivationsSetRelTest] = ...
        statisticsBetterTrainSetRelevance(Model, scores.ratioCorrectActivationsTrain, scores.ratioCorrectActivationsTest, i, 'better_train');   
    
   [scores.meanRatioCorrectCorrectActivationsSetRelTrain, scores.meanRatioCorrectCorrectActivationsSetRelTest, ...
        scores.stdRatioCorrectCorrectActivationsSetRelTrain, scores.stdRatioCorrectCorrectActivationsSetRelTest] = ...
        statisticsBetterTrainSetRelevance(Model, scores.ratioCorrectCorrectActivationsTrain, scores.ratioCorrectCorrectActivationsTest, i, 'better_train');   

   [scores.meanRatioCorrectErrorActivationsSetRelTrain, scores.meanRatioCorrectErrorActivationsSetRelTest, ...
        scores.stdRatioCorrectErrorActivationsSetRelTrain, scores.stdRatioCorrectErrorActivationsSetRelTest] = ...
        statisticsBetterTrainSetRelevance(Model, scores.ratioCorrectErrorActivationsTrain, scores.ratioCorrectErrorActivationsTest, i, 'better_train');       

   [scores.meanRatioErrorActivationsSetRelTrain, scores.meanRatioErrorActivationsSetRelTest, ...
        scores.stdRatioErrorActivationsSetRelTrain, scores.stdRatioErrorActivationsSetRelTest] = ...
        statisticsBetterTrainSetRelevance(Model, scores.ratioErrorActivationsTrain, scores.ratioErrorActivationsTest, i, 'better_train');  
    
   [scores.meanRatioErrorCorrectActivationsSetRelTrain, scores.meanRatioErrorCorrectActivationsSetRelTest, ...
        scores.stdRatioErrorCorrectActivationsSetRelTrain, scores.stdRatioErrorCorrectActivationsSetRelTest] = ...
        statisticsBetterTrainSetRelevance(Model, scores.ratioErrorCorrectActivationsTrain, scores.ratioErrorCorrectActivationsTest, i, 'better_train');    
    
   [scores.meanRatioErrorErrorActivationsSetRelTrain, scores.meanRatioErrorErrorActivationsSetRelTest, ...
        scores.stdRatioErrorErrorActivationsSetRelTrain, scores.stdRatioErrorErrorActivationsSetRelTest] = ...
        statisticsBetterTrainSetRelevance(Model, scores.ratioErrorErrorActivationsTrain, scores.ratioErrorErrorActivationsTest, i, 'better_train');      
    
end